version: '3.3'
services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=octopus
      - MYSQL_DATABASE=${MYSQL_DATABASE:?err}
      - MYSQL_USER=${MYSQL_USER:?err}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?err}
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000