{
 "title": "Geographical distribution",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Distribution by country",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  last_modified_time AS \"time\",\n  country_iso_code AS metric,\n  count\nFROM country\nWHERE\n  country_iso_code is not null and\n  $__timeFilter(last_modified_time)\nORDER BY last_modified_time"
    }
   ]
  },
  {
   "title": "Distribution by continent",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  last_modified_time AS \"time\",\n  continent_name AS metric,\n  count\nFROM continent\nWHERE\n  continent_name is not null and\n  $__timeFilter(last_modified_time)\nORDER BY last_modified_time"
    }
   ]
  },
  {
   "title": "Top 10 cities",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  last_modified_time AS \"time\",\n  city_name AS metric,\n  count\nFROM city\nWHERE\n  city_name is not null and\n  $__timeFilter(last_modified_time)\nORDER BY count DESC\nLIMIT 10"
    }
   ]
  }
 ]
}